name: Do things every 5 minutes
on:
  schedule:
    - cron: "*/15 * * * *"


jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - run: node tweet.js
        env:
          API_KEY={{ secrets.API_KEY }}
          API_SECRET={{ secrets.API_SECRET }}
          USER_TOKEN={{ secrets.USER_TOKEN }}
          USER_SECRET={{ secrets.USER_SECRET }}