name: Do things every 5 minutes
on:
  schedule:
    # - cron: "0 1 * * 1-5"
    - cron: "*/5 * * * *"


jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: npm i
      - run: node tweet.js
        env:
          API_KEY: {{ secrets.API_KEY }}
          API_SECRET: {{ secrets.API_SECRET }}
          USER_TOKEN: {{ secrets.USER_TOKEN }}
          USER_SECRET: {{ secrets.USER_SECRET }}