name: Check auth setup
on: [pull_request]


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: npm i
      - run: node check.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          USER_SECRET: ${{ secrets.USER_SECRET }}
